#Site properties
name: Paqueil Ixchel


#Link Properties
links:
  products:
    enabled: true
    label: Productos
    url: /
  about:
    enabled: true
    label: Acerca de Mi
    url: /about_me.html
  contact:
    enabled: false
    label: Contactanos
    url: /contactanos.html

order:
  order_link: https://wa.me/5215520678599
  order_text: Me%20intereso%20este%20producto%20
  order_label: Ordernar

#Host name
url: https://paqueilixchel.github.io

